services: 
 frontend:
  build: ./frontend
  ports:
    - "3000:3000"
  networks:
   - jssish_netowrk
 backend:
  build: ./backend
  ports:
   - "8000:8000"
  networks:
   - jssish_netowrk
 database: 
  networks: 
   - jssish_netowrk

# volumes: 
#  #database volume

networks:
  jssish_netowrk: {}