services: 
#  frontend:
#   build: ./frontend/
#   container_name: frontend
#   ports: 
#    - "3013"
#   networks:
#    - "jssish-network"

 backend:
  build: ./backend/
  container_name: backend
  ports: 
   - "3014:3014"
  networks:
   - "jssish-network"
  depends_on:
   - Database
    
 
 Database: 
  image: postgres:latest
  container_name: Database
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: k3sadm
   POSTGRES_PASSWORD: jss1234
   POSTGRES_DB: conference
   POSTGRES_HOST: localhost   
  networks:
   - "jssish-network"

networks:
  jssish-network: {}


#docker run -d --name database -e POSTGRES_USER=k3sadm -e POSTGRES_PASSWORD=jss1234 -e POSTGRES_DB=conference -p 5432:5432 -v postgres_data:/var/lib/postgresql/data --restart unless-stopped postgres:latest
