services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=k3sadm
      - POSTGRES_PASSWORD=jss1234
      - POSTGRES_DB=conference
      - POSTGRES_HOST=database   # Change to service name
    networks:
      - jssish-network

networks:
  jssish-network: {}
